/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/acercade` | `/acercade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/gastos` | `/gastos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/objetivoAhorro` | `/objetivoAhorro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/targetas` | `/targetas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Stack)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Stack)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/notification/notify`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/acercade` | `/acercade`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/ajustes` | `/ajustes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/categorias` | `/categorias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/gastos` | `/gastos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/objetivoAhorro` | `/objetivoAhorro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Drawer)'}/targetas` | `/targetas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Stack)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Stack)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/notification/notify`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/acercade${`?${string}` | `#${string}` | ''}` | `/acercade${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/ajustes${`?${string}` | `#${string}` | ''}` | `/ajustes${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/categorias${`?${string}` | `#${string}` | ''}` | `/categorias${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/gastos${`?${string}` | `#${string}` | ''}` | `/gastos${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/objetivoAhorro${`?${string}` | `#${string}` | ''}` | `/objetivoAhorro${`?${string}` | `#${string}` | ''}` | `${'/(Drawer)'}/targetas${`?${string}` | `#${string}` | ''}` | `/targetas${`?${string}` | `#${string}` | ''}` | `${'/(Stack)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(Stack)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/notification/notify${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/acercade` | `/acercade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/gastos` | `/gastos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/objetivoAhorro` | `/objetivoAhorro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Drawer)'}/targetas` | `/targetas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Stack)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Stack)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/notification/notify`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
